### ISSUE TITLE
Moment of confusion with ~/.tarbell/settings.yaml

### ISSUE THREAD

**Issue by dlh01** [tarbell-project/tarbell#75]
I was tripped up when creating a project with 0.9-beta3 by the sample configuration at http://tarbell.readthedocs.org/en/0.9-beta3/configuring.html.

I thought that if I included `default_s3_access_key_id`, `default_s3_secret_access_key`, and `default_s3_buckets` in `settings.yaml`, then I wouldn't need to supply `s3_credentials` to deploy to the default buckets. But `tarbell publish` returned `KeyError: 's3_credentials'`. 

Specifying `s3_credentials` along with my `production` and `staging` URLs caused `tarbell publish` to use the default keys. My `settings.yaml` now includes:

```
default_s3_access_key_id: [...]
default_s3_secret_access_key: [...]
default_s3_buckets:
    production: projects.religionnews.com
    staging: projects.beta.religionnews.com
s3_credentials:
  projects.beta.religionnews.com:
  projects.religionnews.com:
```

without any keys under `s3_credentials`. That's fine, but I thought I would mention the confusion. Apologies if I missed something in the docs about it.

That said, apart from this issue and #74, working with beta3 on this new project has been great. Thanks so much for continuing to develop Tarbell.
